# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89b72f96cab6c7e514c3fa21c2572d9004f508e0b453359bdb122760eefaf562a0a88418da1c370d054c0a9e2a6604faadbad253b6ca7909f06c8fba6c164291

test:
  secret_key_base: e23a36a96c96356f7b684236a7f7ce3d101cca4ac1295ba43dfa023e89f772f369bd493820ebd12ec2fc87dbb6bedc91d24f4d0afc886a7378ffe01f29bfabcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
